requires = ["tox>=4"]
env_list = ["lint", "py39", "py310", "py311", "py312", "py313"]

[env_run_base]
description = "run unit tests"
deps = [
    "pytest>=8",
    "pytest-sugar"
]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]

[env.lint]
description = "run linters"
skip_install = true
deps = ["ruff"]
commands = [
    ["ruff", "check", "."]
]