services:
  gpucontainertest:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    ipc: "host"
    ulimits:
      memlock: -1
      stack: 67108864